### ISSUE TITLE
Add fly deploy Github Workflow

### ISSUE THREAD

**Issue by KalebMills** [devict/keeper#1]
We need to be able to get Keeper deployed into the [fly.io](https://fly.io) environment to be able to interact with keeper via the DevICT slack. It should be nearly identical to what we have [here](https://github.com/devict/job-board/blob/8e7290f9c2550d388ee1ee7599b807cde71aacd0/.github/workflows/main.yml)

**Comment by sethetter** [comment]
Closed with #3
